development: &default
  secret_key_base: 191c3e520eb4cc3a2c416fb9fbfcdb8ebf2dc92fff202ed1ff39ece41d6d36aca6035ecc4bb1cc43efe8aeb8c2d869a161277a55c71238b6fec6ab7b753ded89
  postmark_key: <%= ENV['POSTMARK_KEY'] %>

test:
  <<: *default
  postmark_key: POSTMARK_API_TEST
  secret_key_base: 66927f7d72f6db49915893f11c49995d298a1cf0a07c2498386e9129483ad114655507ddee57377462a6fcdc4bde8b5fc38e023a5d1743d3473ddebb670d985a

staging: &deployed
  <<: *default
  aws_key: <%= ENV['AWS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] || 'us-east-1' %>
  aws_secret: <%= ENV['AWS_SECRET'] %>
  default_url_host: <%= ENV['DEFAULT_URL_HOST'] %>
  ga_tracking_id: <%= ENV['GA_TRACKING_ID'] %>
  http_basic_pass: <%= ENV['HTTP_BASIC_PASS'] %>
  http_basic_user: <%= ENV['HTTP_BASIC_USER'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

production:
  <<: *default
  <<: *deployed
